# Generated by Django 2.0.4 on 2018-04-12 23:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('formData', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='TemplateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsonSchema', django.contrib.postgres.fields.jsonb.JSONField()),
                ('uiSchema', django.contrib.postgres.fields.jsonb.JSONField()),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='instancemodel',
            name='template_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foreignform.TemplateModel'),
        ),
    ]
