# Generated by Django 2.0.4 on 2018-04-13 01:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foreignform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancemodel',
            name='formData',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='templatemodel',
            name='uiSchema',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=True),
        ),
    ]
