# Generated by Django 2.0.4 on 2018-04-13 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foreignform', '0002_auto_20180413_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instancemodel',
            old_name='formData',
            new_name='form_data',
        ),
    ]
