# Generated by Django 2.0.4 on 2018-04-13 04:13

from django.db import migrations
import foreignform.fields


class Migration(migrations.Migration):

    dependencies = [
        ('foreignform', '0003_auto_20180413_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancemodel',
            name='form_data',
            field=foreignform.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='templatemodel',
            name='jsonSchema',
            field=foreignform.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='templatemodel',
            name='uiSchema',
            field=foreignform.fields.JSONField(blank=True, default=True),
        ),
    ]
