# Generated by Django 2.0.4 on 2018-04-13 05:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foreignform', '0004_auto_20180413_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancemodel',
            name='form_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
