# Generated by Django 2.0.4 on 2018-04-13 06:19

from django.db import migrations
import foreignform.fields


class Migration(migrations.Migration):

    dependencies = [
        ('foreignform', '0005_auto_20180413_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatemodel',
            name='uiSchema',
            field=foreignform.fields.JSONField(blank=True, null=True),
        ),
    ]
