# Generated by Django 2.0.4 on 2018-04-13 16:28

from django.db import migrations
import foreignform.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatemodel',
            name='jsonSchema',
            field=foreignform.fields.JSONField(blank=True, null=True),
        ),
    ]
